### ISSUE TITLE
[bug] Empty interface when launching Meshroom

### ISSUE THREAD

**Issue by dylanc0te** [alicevision/meshroom#1183] opened 2020-12-16 17:00 UTC
Hello everyone,

Here is my bug : 

I just download the latest version of Meshroom for Windows, but when I launch it, I get that empty interface, with some strange strobs  : 

![bug_meshroom](https://user-images.githubusercontent.com/32870428/102380687-81493600-3fc8-11eb-820f-9bed1260db44.jpg)

I'm on a new PC laptop, with RTX 2070 and a Intel I7.
The other software works great on this computer.
Meshroom works great on my other computer.

Have you got an idea about that ?
Thanks !

**Comment by natowi** [comment] 2020-12-16 17:21
Duplicate of https://github.com/alicevision/meshroom/issues/1093

Try running Meshroom in Windows 8 compatibility mode

**Comment by dylanc0te** [comment] 2020-12-16 19:40
Thanks, it's working ;)

**Closed** 2020-12-16 19:54 UTC
Labels: bug
