### ISSUE TITLE
Reconstruction "grows" artifacts into neutral background

### ISSUE THREAD

**Issue by ALfuhrmann** [alicevision/Meshroom#566] opened 2019-07-30 09:50 UTC
I am using a rotating stage in front of a diffusely lighted white background to avoid specular highlights. I get excellent image quality of the objects in front of a white saturated background. 

While all the cameras get positioned correctly and the objects themselves get reconstructed without holes and with very little noise, they also exhibit strange artifacts "growing" from the end of the object into the background (image attached).
![image](https://user-images.githubusercontent.com/3731183/62119484-fa56c900-b2bf-11e9-8cf1-0f0aff3a7454.png)

The artifacts "mirror" and continue part of the objects profile, even though the images show only evenly illuminated background.

I could avoid this easily by using an (automatically generated) mask for each image (see #188), but at the moment I could only post process the model by removing any geometry with background color.

So, how can I remove these artifacts?

**Comment by natowi** [comment] 2019-07-30 11:13
I think this error is caused by texture/pattern similarity resulting in inaccurate feature detection in this area. 
There will be a Features Viewer in the upcoming release which might help to find the cause for this problem.
You could try with [AKAZE and/or High settings](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters) to get more features detected and increase the accuracy.

**Comment by ALfuhrmann** [comment] 2019-07-30 13:14
I will try this, but I already get quite a large amount of features in the sparse reconstruction, over 34000, and none of them in the volume where the artifacts appear:
![image](https://user-images.githubusercontent.com/3731183/62131682-e751f200-b2db-11e9-9d22-0c1d93b23cfc.png)
 All this additional geometry seems to appears at the depthmap stage:
![image](https://user-images.githubusercontent.com/3731183/62132004-8d9df780-b2dc-11e9-810f-79b10f45c67b.png)
It looks like a reconstruction of spurious features in the depth map of the background.

**Comment by natowi** [comment] 2019-07-30 14:51
> Which parameters do your mean by (Min values camera/pairs)? In the Depthmaps, the Neighbour cameras?

I would try increasing the SGM: Nb Neighbour Cameras, Refine: Nb Neighbour Cameras values and compare the results.

Basically use the information provided in the [wiki](https://github.com/alicevision/meshroom/wiki/Reconstruction-parameters) to increase the density of your reconstruction.

**Comment by ALfuhrmann** [comment] 2019-07-30 19:04
So I turned up the SFM with AKAZE and High setting, and switched the SGM and Refine neighbour to 10 and 6. Now I got 135.000 sparse points, a very nice model and still the same artifacts.

In the picture below I compare one depth map with the result model from approximately the same camera. The artifacts growing from the tip of the key seem to be parallel to the scanline artifacts in the depthmap:
![image](https://user-images.githubusercontent.com/3731183/62157300-1df43080-b30d-11e9-9f4f-d234a0783a90.png)
My hypothesis is that the uniformly white background behind the key delivers no features, so the depthmap calculation extends via belief propagation some features of the object into the background. And since the features correspond loosely to the tip of the rotating object, the meshing node produces these artifacts.
What do you think?

**Comment by SquidLord** [comment] 2019-07-30 19:09
This is one of the strong reasons that you should probably avoid featureless backgrounds for scanning. Once the algorithm is looking really hard for variations in a surface in order to get an idea of where it is, tiny become enormously important to it.

In most cases, you would be better off putting your target on a sheet of newspaper with all of its texture and type then you are putting it on a featureless white field. It's easy enough to clean up the model after the fact and remove a properly visible surface.

**Comment by ALfuhrmann** [comment] 2019-07-30 20:26
Point taken, but in this case I have reflective objects, which I can reconstruct only under a diffuse environment. I did this in Agisoft Photoscan by simply adding masks which I can easily pull from background.
So I'm thinking of three option:
1. color-key the background and remove everything colored from the final model
2. put in a rendered textured background generated for the camera positions
3. mask the depthmaps with masks generated from the undistorted images

(1) is a dirty hack, (2) does essentially what you proposed in post, and (3) would probably fix the cause of the problem, but I am not sure if it works. If (3) worked, I could write a new node which takes masks, undistorts them and subtracts them from the depthmaps after filtering.

Any suggestions? Would (3) be feasible?

**Comment by dmontagu** [comment] 2019-07-31 00:26
I'm also curious about depthmap masking -- if it plays nice with the subsequent meshing steps, I think it could help a lot of use cases (e.g. automated background removal) considering the extent of resources available for automated image processing relative to automated point-cloud/mesh processing.

**Comment by SquidLord** [comment] 2019-07-31 02:52
It actually might be more effective to matte spray your reflective objects to remove their reflectivity. That's going to be problematic for a lot of reasons anyway so you'll be saving yourself a lot of reconstruction problems in the long run. A lightly tacky matte spray and some powder to actually give the system some detail to work with is always going to be better than trying to work with reflective objects.

Theoretically, dropping an object mask on the original images would only provide data for the object. In actual practice, however, I find that the resulting reconstruction even on near ideal objects like wood bark and textured rock to never be quite as good at capturing camera positions as having a real background which provides parallax with the object.

But that's my experience.

Putting in a rendered background based on what's ultimately an approximated camera position (because the digital environment is never going to perfectly match up with the real world camera) would seem to be borrowing the worst of all worlds. Even an empty mask has got to be better than that.

**Comment by ALfuhrmann** [comment] 2019-07-31 07:55
__@SquidLord__: For my application, a modification of the object is not possible. I already tried white spray chalk for getting a ground truth using a laser scanner, but removing this is a pain, which would not work in the proposed workflow. Additionally I am using extreme closeup macro to get the necessary resolution and precision. Adding any kind of layer thickness is not helping. Using cyclododecane spray would work, since this just vanishes by sublimation, but you need a relatively thick, waxy layer which exhibits subsurface scattering. For tiny objects, the layer thickness is prohibitive.

The reconstruction itself works fine, the only problems I get are with symmetric objects (naturally). Matching a rendered environment up with the real world camera is probably not so difficult, since I would do this after SFM, where I already have a calibrated camera and undistorted images, which I can use to align the render camera. But this would be a stupid workaround, not fixing the cause of the problem.

And since masking works in Photoscan & Reality Capture, I think it would be a useful enhancement to the workflow. I just need to know if the depthmaps are generated from the same point of view as the associated undistorted images. It would be nice to consider the masks for SFM, too, but I have no idea how.

**Comment by natowi** [comment] 2019-07-31 09:35
@ALfuhrmann Yes, featureless background can have its drawbacks, as @SquidLord explained. 

You could try enabling AKAZE in the FeatureMatching node. FeatureMatching matches the Features from FeatureExtraction, so it can work like a filter. Modifying the Distance Ratio can reduce outliers.
You can also experiment with the settings in DepthMapFilter.

One other thing would try: do not place the key on a flat surface, place something underneath. This will enable you to better capture the edges.

This does not work, I think masking would be the best way to go in your case.

> I could write a new node which takes masks, undistorts them and subtracts them from the depthmaps after filtering.

This would be a good and welcome contribution https://github.com/alicevision/meshroom/issues/188

**Comment by ALfuhrmann** [comment] 2019-07-31 14:08
@natowi So now I just have to figure out WHICH maps to mask: What is the difference between depthMap, simMap, and nmodMap? Do I have to walk through the source code, or is this documented somewhere?

**Comment by natowi** [comment] 2019-08-01 13:43
I think simMap=SGM optimized similarity volume, depthMap=depthMap, nmodMap=for filtering
You can look into the references at https://alicevision.org/#photogrammetry/depth_maps_estimation

**Comment by ALfuhrmann** [comment] 2019-08-01 15:05
Great, thanks!
I already tried masking all of them to zero, but it didn't work. Have to check out those references.
Shall I close the issue, or use this to pester you with further questions?

**Comment by natowi** [comment] 2019-08-01 16:26
You can keep it open.

**Comment by hargrovecompany** [comment] 2019-08-05 01:00
weird things have happened for me when the foreground object occupies a small percentage of the image, and the background is either featureless or has a consistent pattern.  If possible, zoom in even closer for the pics.

**Comment by ALfuhrmann** [comment] 2019-08-28 15:37
Back from my holidays, I am looking into the mask issue again.

I first tried simply masking the depth images using imagemagick, but only got errors from the meshing node. Now I am trying a python script which reads the .EXR images and masks them.

The only thing I need to know now is with what values to replace the masked areas.
Both image types (depthmap & simmap) contain a border with constant values, I presume to compensate for the image edges when doing a convolution or comparison. These values (-1.0 and 1.0 respective) are possible candidates for masking values.

Does someone know if this could work? Or any other values?

**Comment by fabiencastan** [comment] 2019-08-28 21:32
Yes -1.0 in depth map means invalid.

**Comment by ALfuhrmann** [comment] 2019-09-02 11:58
So I wrote a short python script which takes .PNG masks as input and masks the *_depthMap.exr output of _DepthMapFilter_. First results look promising:
Source image and mask:
![image](https://user-images.githubusercontent.com/3731183/64112467-c7549900-cd87-11e9-8a5a-24d5a66fc4f4.png)
And here the result from _Meshing_, without and with masking:
![image](https://user-images.githubusercontent.com/3731183/64112560-11d61580-cd88-11e9-920d-c1eb35ec6c98.png)

At the moment the script is called outside of Meshroom, I now have to convert it into a node.

At the moment I just use mask files generated with ImageMagick from the source images. I put these into a separate folder and call my script with this folder, the depthmap folder, and the .sfm file as parameters. For now, I would like to build a node which does exactly this, meaning that the masks can be generated outside of meshroom, or - later - with a Meshroom node with a more sophisticated masking approach (adaptive thresholding,  GrabCut, or something discussed in #188).

So, is there a documentation how to implement a new node, or do I have to extract this from the source?

**Comment by ALfuhrmann** [comment] 2019-09-03 12:59
I looked through the node sources and figured it out.

Now I have a minimalistic node, which has the filtered depth maps and the undistorted masks as input and outputs masked depth maps for meshing:

![image](https://user-images.githubusercontent.com/3731183/64174657-0521f200-ce5a-11e9-84d6-3cb169699d72.png)

The _PrepareScene2_ node above has as input the folder of the mask images. DeptMaskFilter has only the following Attributes:

![image](https://user-images.githubusercontent.com/3731183/64174780-45817000-ce5a-11e9-8856-9dacc7f0d1e9.png)

_Masks Folder_ is the output from  _PrepareScene2_, the other inputs are the same as for _Meshing_.

Currently I build the masks externally with Imagemagick floodfill, but a node for creating masks with one of [this methods](https://github.com/natowi/masking_tools/blob/master/README.md) would be the logical next step.

Anyone interested in testing this?

**Comment by ALfuhrmann** [comment] 2019-09-04 09:31
Here is everything you should need for testing:

[masking_patch.zip](https://github.com/alicevision/meshroom/files/3573743/masking_patch.zip)

Copy the "lib" folder from the ZIP in your meshroom root folder, merging it with the "lib" in there.
At the moment it is only tested with Meshroom-2019.1.0-win64, but it probably works with 2019.2.0, too.

The ZIP also contains a sample Meshroom graph "Meshroom-2019.1.0-win64", which shows the necessary nodes and connections.

So you need only to drop your images in Meshroom, and put the folder where your masks are in the "DepthMaskFilter/Mask Folder" attribute.
Masks are named like the source image they belong to, and have to be grayscale .PNG files. Every pixel with value 0 (black) is masked (see [here](https://github.com/alicevision/meshroom/issues/566#issuecomment-527121184)).

Please post your results in this thread.

**Comment by ALfuhrmann** [comment] 2019-09-05 07:02
Reconstruction of a reflective key, real life case:
(taken with a turntable and diffuse illumination)

Input image (one of 40):
![image](https://user-images.githubusercontent.com/3731183/64318907-762ceb00-cfbb-11e9-90ec-b76e40d69de9.png)


Without masks:
![image](https://user-images.githubusercontent.com/3731183/64318946-8c3aab80-cfbb-11e9-9c2d-a6a236e7d027.png)

With masks (generated with Imagemagick):
![image](https://user-images.githubusercontent.com/3731183/64318967-99f03100-cfbb-11e9-88cc-5275952f4440.png)
(no post processing, only MeshFiltering node)

**Comment by ALfuhrmann** [comment] 2019-09-11 12:51
@natowi: I have now a first implementation of a "Depthmask" node, as well as quick implementation for the mask generation (python w/OpenCV) which I could also put in a node.

I'd like to generate a pull request, since the patch I posted above is not something one could reliably use. 

Since my node is at the moment written in Python, I need some information how to add it to the build:

- How and where to add the additional python modules I need? (OpenEXR, numpy, etc.)
- How to cleanly implement logging in a pure Python node (without commandline executable in it)
- and probably some other stuff, too.

So, do I open a new issue, is there someone I can contact directly? I'd prefer a forum, so that others get these answers, too

**Comment by fabiencastan** [comment] 2019-09-14 09:10
Hi @ALfuhrmann,
It would be good to start a PR as "WIP" when you start, so we can see your implementation and propose modifications.

- "How and where to add the additional python modules I need? (OpenEXR, numpy, etc.)"

I'm still not sure if we want to that instead of just implementing it in C++ in AliceVision, but at least it's a good way to prototype. For small nodes that may evolves a lot, I agree that it could be cool to do it in python but I'm not sure if this short term simplification will not become a long term nightmare.
So as a start I would recommend to create a new folder in `meshroom/nodes/YourNodeGroup` with a python `requirements.txt` file in it. If it's a painful for packaging, we could move it to C++ later.
What do you think?

- "How to cleanly implement logging in a pure Python node (without command line executable in it) and probably some other stuff, too."

I would recommend to use logging for now even if it's not included in the log file for now.
This [PR](https://github.com/alicevision/meshroom/pull/631) would be a good way to do it, but needs to provide a standard logging object instead of a custom one.
So at the end, you would be able to replace your calls to `logging` by this object.

**Comment by ALfuhrmann** [comment] 2019-09-17 11:16
I submitted a [pull request](https://github.com/alicevision/meshroom/pull/641).

I think everything should be included there, please contact me if I messed up.

**Comment by natowi** [comment] 2019-11-16 19:35
@ALfuhrmann I put together a [ImageMasking node](https://github.com/natowi/meshroom_external_plugins) to auto-generate masks for images with white background based on ImageMagick.

**Comment by daktylus** [comment] 2020-03-23 09:49
Hi  @ALfuhrmann,

I am impressed by the detail on your scan of the key. I always struggle with metallic surfaces. Can you show some more details on your scanning setup and perhaps some more examples?

**Comment by natowi** [comment] 2020-03-23 13:37
@daktylus Use a Lightbox and a turntable. You need diffuse light to reduce reflections to a minimum.
(_If possible_, cover your metallic surfaces with a thin layer of paint or something similar.)
If you still have questions, please open a new issue with a detailed description of your current setup, and what object you are trying to capture, as this is not directly issue related.

**Comment by ALfuhrmann** [comment] 2020-03-23 17:05
Exactly what @natowi said: I've been using a white plastic dome for light diffusion. Try to avoid reflections as much as possible-

You can use a chalk spray (the stuff you can use for outdoor markings), but if you use it on keys it might gunk up the lock afterwards.

Additionally, I use a heavy macro lens, which makes the scratches and imperfections visible.

**Comment by tkircher** [comment] 2020-04-05 13:17
@natowi is there a good explanation for the fact that sparse reconstructions can accurately reproduce objects in a scene but further steps in the pipeline introduce noise? There are a handful of other issue reports pertaining to this, where objects disappear from a scene. You always give the same advice, to change the field of view and so on, but that is never actually necessary for the sparse reconstruction. Isn't there a way to use the almost always perfectly accurate SFM output to reject points outside of the sparse cloud?

**Comment by P3rf3ctDay** [comment] 2020-04-24 04:41
> Please post your results in this thread.

I'm a little late to the party, but interested in this topic.
I attempted to use the masking_patch.zip that @ALfuhrmann posted on Sept 4, 2019. I'm using Meshroom-2019.2.0-win64 and encountered two issues. I understand that this is under development and appreciate the work that has been put into this project. If there is a more recent development that I should be using, I'd love to look at those resources.

Once the lib files are extracted from the masking_patch.zip and merged into Meshroom-2019.2.0-win64\Meshroom-2019.2.0\lib, I opened Meshroom to receive the following error:
![Incompatible](https://user-images.githubusercontent.com/64242493/80175322-46bb0500-85c3-11ea-9b9b-2665580d0d22.JPG)
The second issue arises when trying to load images, regardless if I upgrade the nodes to the current version (or not). The path to the camera sensor seems to have been hard coded into the patch.

Plugins loaded:  CameraCalibration, CameraInit, CameraLocalization, CameraRigCalibration, CameraRigLocalization, ConvertSfMFormat, DepthMap, DepthMapFilter, DepthMaskFilter, ExportAnimatedCamera, ExportColoredPointCloud, ExportMaya, FeatureExtraction, FeatureMatching, ImageMatching, ImageMatchingMultiSfM, KeyframeSelection, LDRToHDR, MeshDecimate, MeshDenoising, MeshFiltering, MeshResampling, Meshing, PrepareDenseScene, Publish, SfMAlignment, SfMTransform, StructureFromMotion, Texturing
**WARNING:root:Compatibility** issue detected for node 'PrepareDenseScene_1': VersionConflict
**WARNING:root:Compatibility** issue detected for node 'DepthMapFilter_1': VersionConflict
**WARNING:root:Compatibility** issue detected for node 'MeshFiltering_1': VersionConflict
**WARNING:root:Compatibility** issue detected for node 'Texturing_1': VersionConflict
**WARNING:root:Compatibility** issue detected for node 'Meshing_1': VersionConflict
**WARNING:root:Compatibility** issue detected for node 'PrepareDenseScene_2': VersionConflict
**WARNING:root:Compatibility** issue detected for node 'Meshing_2': VersionConflict
**WARNING:root:Compatibility** issue detected for node 'MeshFiltering_2': VersionConflict
Program called with the following parameters:
 * allowSingleView = 1
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:\Users\vr2\AppData\Local\Temp\tmpl9mjm681/CameraInit/f1e2eb85ff47e36189d984889fbb64df6e81993a//viewpoints.sfm"
 * output = "C:/Users/vr2/AppData/Local/Temp/tmpl9mjm681/CameraInit/f1e2eb85ff47e36189d984889fbb64df6e81993a/cameraInit.sfm"
 * **sensorDatabase = "C:/Meshroom-2019.1.0/aliceVision/share/aliceVision/cameraSensors.db"**
 * verboseLevel = "info"

[00:24:04.159229][error] Invalid input database 'C:/Meshroom-2019.1.0/aliceVision/share/aliceVision/cameraSensors.db', please specify a valid file.
ERROR:root:Error while building intrinsics : Traceback (most recent call last):
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\meshroom\ui\reconstruction.py", line 399, in buildIntrinsics
  File "C:\Users\DEV\AppData\Local\Temp\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 192, in buildIntrinsicsRuntimeError: CameraInit failed with error code 1. Command was: "aliceVision_cameraInit  --sensorDatabase "C:/Meshroom-2019.1.0/aliceVision/share/aliceVision/cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --verboseLevel info --output "C:/Users/vr2/AppData/Local/Temp/tmpl9mjm681/CameraInit/f1e2eb85ff47e36189d984889fbb64df6e81993a/cameraInit.sfm" --allowSingleView 1  --input "C:\Users\vr2\AppData\Local\Temp\tmpl9mjm681/CameraInit/f1e2eb85ff47e36189d984889fbb64df6e81993a//viewpoints.sfm""

Thanks in advance for your kind advice.

**Comment by natowi** [comment] 2023-07-25 19:45
The latest version of Meshroom supports Masking, which should solve this issue:
https://github.com/alicevision/Meshroom/wiki/New-Features-in-Meshroom-2023.1#1-image-masking

**Closed by natowi** 2023-07-25 19:45 UTC
Labels: type:question, do not close
