### ISSUE TITLE
Is there any new release on the way?

### ISSUE THREAD

**Issue by zhangalex** [alicevision/meshroom#525] opened 2019-06-25 08:33 UTC
Hi MeshRoom authors,

First of all, thank you very much for the effort on the great software, we are testing the project, and we feel this is really very cool work.  I notice that a lot of contributors are working day and night on the project, but after a half year there is no new release comes yet. So, my question is that is there any schedule on the next release? 

Actually, I'm compiling the source code from develop branch, but after I tested I found a lot of difference behaves compare to version 2019.1. For example, we are trying to scan a human face using MeshRoom, the ver. 2019.1 can successfully construct the whole face (but the 3d model has a lot of holes on the surface the human face, not very smooth), but the latest develop branch version can only construct half of the human face. I understand that develop branch is under development, it has bugs are reasonable. For me, it very hard to understand the source code of this project since I'm a newbie on the 3d reconstruction field, maybe I need more 1 year get well understand the source code and the theory.

Thanks,
Alex

**Comment by fabiencastan** [comment] 2019-06-26 08:59
Identifying a regression and sending it to us for analysis is an invaluable contribution.

Could you check if the problem doesn't not simply come from a change in the sensor database?
We have already seen this problem, like for instance https://github.com/alicevision/meshroom/issues/495.
Else could you send us a dataset that works better in the release 2019.1 than in the develop branch? You can use the private mailing-list: alicevision-team@googlegroups.com

If there is a real regression, it may post-pone the release.

**Comment by Goggen240** [comment] 2019-06-28 12:22
Not to butt into this conversation, but this seems like the right thread to ask; you mentioned that the new release was on the way; what's the (rough) timeline with or without postponement?
The previous estimate was middle of May, but that's passed, and I've been waiting for the new version since I'm stuck on 2018.1.0 because of that bug where it won't process projects where there are unmatched photos.
Not that I'm complaining, MeshRoom is an awesome project, and I'm certainly getting more than I'm paying for. I'm just messing around with it as a hobby, but I'm very grateful for the tremendous job you've all done!
Keep up the good work!

**Comment by natowi** [comment] 2019-06-28 15:10
[Alicevision 2019.2 ](https://github.com/alicevision/AliceVision/milestone/30) is nearly complete and for Meshroom[ a few pull requests](https://github.com/alicevision/meshroom/pulls) need to be merged.

**Comment by Goggen240** [comment] 2019-06-29 09:31
That's excellent news, terrific!

**Comment by simogasp** [comment] 2019-08-17 13:16
https://github.com/alicevision/meshroom/releases/tag/v2019.2.0

**Closed by simogasp** 2019-08-17 13:16 UTC
