### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by Crunchie52** [alicevision/meshroom#1224] opened 2021-01-13 12:28 UTC
I am evaluating the use of photogrammetry & Meshroom to reverse engineer components of vintage machinery and thus far have some encouraging results albeit with a few challenges. Scaling with markers (CCTags) is a mandatory requirement, and  orientation/positioning  of the object is highly desirable before transferring to CAD system. I have been unable to produce a correct dense cloud/mesh after using SfMTransform to scale & position the StructureFromMotion output.

Numerous subjects/image sets have been tried, all with the same result - the Dense Cloud is incorrect, it tends to be something like a small "wrapper" of part of the sparse cloud. It seems that the information passed to DepthMap by SfMTransform is incomplete or incorrect for DepthMap to do its job correctly.

Perhaps the problem is mine, or perhpaps it is a bug? I don't know, so have initially posted as a question with example shown below.

Test Example: 
Using relatively small set of 141 images to reverse engineer a cylinder head, these reconstruct perfectly using the default Meshroom workflow. The CCtags form a square having sides of 120mm:
![A -example image](https://user-images.githubusercontent.com/77319761/104448599-ad42e180-559d-11eb-85ac-b2cc40829edc.PNG)
A SfMTransform Node is inserted as shown:
![B -nodes](https://user-images.githubusercontent.com/77319761/104451252-90a8a880-55a1-11eb-9272-1c6b44538b48.PNG)
![C -SfMTransform](https://user-images.githubusercontent.com/77319761/104451260-930b0280-55a1-11eb-8133-7ef7cbf36fe3.PNG)
The output of StructureFromMotion (before Transform) is:
![D -Sparse Cloud](https://user-images.githubusercontent.com/77319761/104451361-b7ff7580-55a1-11eb-8dcb-cbd1eb0edc97.PNG)
The output of the SfMTransform, superimposed on the untransformed SfM output. It seems that the transform has correctly scaled and positioned everything!
![E -Sparse Transform](https://user-images.githubusercontent.com/77319761/104451493-e8471400-55a1-11eb-9e51-755a26452620.PNG)
However, Depth Map produces a "nonsensical" dense cloud:
![F -Dense Cloud](https://user-images.githubusercontent.com/77319761/104451654-23e1de00-55a2-11eb-8ca6-d58bd7c7cbda.PNG)
Dense Cloud zoomed:
![G -Dense Cloud Zoom](https://user-images.githubusercontent.com/77319761/104451716-3825db00-55a2-11eb-964b-b6802452b584.PNG)

**Comment by natowi** [comment] 2021-01-13 16:24
Duplicate of https://github.com/alicevision/meshroom/issues/1223

**Closed by natowi** 2021-01-13 16:24 UTC
Labels: type:question
