### ISSUE TITLE
[question] sensor database no edit permission 

### ISSUE THREAD

**Issue by hlyman** [alicevision/meshroom#943] opened 2020-06-13 19:34 UTC
**Describe the problem**
I added my camera Fujifilm FinePix S4250WM to alicevision camerasenor and it won't save giving the message "You do not have permission to open this file. See the owner of the file or an admisnistrator to obtain permission".

**Comment by natowi** [comment] 2020-06-13 19:41
Move the Meshroom folder to a different location on your drive.

**Comment by hlyman** [comment] 2020-06-13 20:22
I uninstalled and installed  Meshroom to a different folder and the camerasenor file still will not save after adding my camera.

The camera I have is a "Fujiflim FinePix S4250WM; s/n 2TB65298

**Comment by natowi** [comment] 2020-06-13 22:01
Open cameraSensors.db in the Editor (right click on file->open with->editor)
Insert the following line in the file and save it:

`Fujifilm;Fujifilm FinePix S4250WM;6.16;usercontribution`

Did you extract the meshroom.zip file in a new folder?
If not, this could be a reason on why you can not edit the file.

As a test, extract the meshroom.zip in your "My documents" folder. There should not be permission problems in that folder.

**Comment by hlyman** [comment] 2020-06-13 22:39
OK I got the camerasensor file updated with my camera and it saved.  Now the problem is that the photos I open in meshroom shows orange instead of green with Metadata showing LG camera.  This may to much for this beginner to learn being only 91 yrs old.

**Comment by natowi** [comment] 2020-06-13 23:56
No problem, Meshroom uses the right data. 

Meshroom looks up the metadata stored in the image file. The Camera Model info does not match my proposed database entry by 100%, but Meshroom correctly uses the closest match. That´s why there is the orange icon. Meshroom will work with this. 

If you want to test it, you can replace the last addition to the database with:

`Fujifilm;FinePix S4250WM;6.16;usercontribution`

> This may to much for this beginner to learn being only 91 yrs old.

I´m impressed! If you have any more questions, feel free to ask.

Here is a good guide for capturing images https://journalists.org/resources/a-guide-to-photogrammetry-photography/

And here are two good Meshroom tutorials:
https://sketchfab.com/blogs/community/tutorial-meshroom-for-beginners/
https://medium.com/realities-io/getting-started-with-photogrammetry-d0a6ee40cb72

**Comment by hlyman** [comment] 2020-06-14 00:10
I'll keep trying.
You can see my things on thingiverse,  "hlyman"

------ Original Message ------

**Comment by hlyman** [comment] 2020-06-16 23:01
OK, I got photos showing correctly.  Did a Start and now have a scene from :StructureFromMotion". But there is no "Load Model" button to show Texturing.  142 of 172 photos were used.  It appears processing stopped at "DepthMap".  Texturing is gray in SETTINGS.

![Screenshot (66)](https://user-images.githubusercontent.com/1063100/84836425-91b52f80-afea-11ea-9ddf-dc7c996d53f2.png)

**Comment by natowi** [comment] 2020-06-17 07:45
Can you click on the DepthMap node and in the Node Settings next to the Attributes tab, click on the Log tab. I assume there is an error message like "[error] This program needs a CUDA-Enabled GPU (with at least compute capability 2.0)". Meshroom needs a Nvidia GPU to compute the DepthMap node. If you have a Nvidia GPU, you need to update the drivers. If you don´t have one, you can use Draft Meshing: https://github.com/alicevision/meshroom/wiki/Draft-Meshing

Your statue is not the best thing to start with photogrammetry: Due to its white colour it has basically no features for the algorithm to detect. If this was a wooded statue, you would have a denser point cloud from the 142 images than you have now. 6011 points are pretty few for this object.

**Comment by hlyman** [comment] 2020-06-18 20:17
Yes I found an error message.
So now I took a polar bear model, painted in a dull gray, made 178 
photos of it.
As I do not have Nvadia I removed nodes, PrepareDenseScene, Depthmap, 
and Depth Filter, to use Depth Meshing. This picture shows where it 
stopped.

------ Original Message ------

**Comment by natowi** [comment] 2020-06-18 20:46
> This picture shows where it stopped.

You did not attach an image.

**Comment by hlyman** [comment] 2020-06-18 22:08
Here is the picture

------ Original Message ------

**Comment by hlyman** [comment] 2020-06-18 22:15
So I tried it again fresh and in FeartureExtracton I got this error 
"[15:10:24.732755][error] cudaGetDeviceCount failed: CUDA driver version 
is insufficient for CUDA runtime version"  I had yesterday downloaded 
CUBA, put I don't know what to do with it.

------ Original Message ------
From: "Hugh" <hlyman@comcast.net>
To: "alicevision/meshroom" 
<reply@reply.github.com>
Sent: 6/18/2020 3:08:40 PM
Subject: Re[2]: [alicevision/meshroom] [question] sensor database no 
edit permission (#943)

**Comment by hlyman** [comment] 2020-06-19 00:25
Even with the error message in FeatureExtraction I let the program 
continue to the end and here is screenshot of the finished product.  
There is not :Load Model" button.


------ Original Message ------
From: "Hugh" <hlyman@comcast.net>
To: "alicevision/meshroom" 
<reply@reply.github.com>
Sent: 6/18/2020 3:15:11 PM
Subject: Re[3]: [alicevision/meshroom] [question] sensor database no 
edit permission (#943)

**Comment by natowi** [comment] 2020-06-19 06:53
Your replies via email don´t contain any images. Please attach the images via Github like you did before.

**Comment by hlyman** [comment] 2020-06-19 14:33
Here is the screenshot
![Screenshot (71)](https://user-images.githubusercontent.com/1063100/85143806-19738780-b1ff-11ea-9006-68a1dad963c6.png)

**Comment by natowi** [comment] 2020-06-19 15:16
Double click on the Texturing node to load the model.

As you can see from the Feature overlay in the Image Viewer, most of the features are detected at your models edges. The main part of the model is too smooth/single coloured, featureless.
You could use a brush to sparkle/scatter paint dots over the model surface with watercolour or add small dots with a pen that can be removed with water to provide more features that can be picked up by the algorithm. (Of course you need to make sure that the paint can be easily be removed from your model)

If need to capture only this kind of objects, you can take a look at the free version of the commercial photogrammetry software [zephyr](https://www.3dflow.net/3df-zephyr-free/) (limited to 50 input images), which is more forgiving and does not require so much tweaking.

**Comment by hlyman** [comment] 2020-06-19 16:59
Can you advise me what nvadia video card I should get for my PC?
I downloaded Zephyr and will try it.

------ Original Message ------

**Comment by natowi** [comment] 2020-06-19 19:02
To really make sure your computer has no Nvidia Graphics Card and the problem is not a missing driver, you can start the command line and run the following command (if you don´t know your precise graphics card):

`wmic path win32_VideoController get name`

--

Giving (remote) advice on hardware configurations is difficult, I would recommend you to ask someone you trust and who has some computer knowledge to help you out (so you don´t get ripped off by stores). Maybe someone from the young generation even has a used Nvidia GPU laying around you can use. 

The _minimum_ requirement for Meshroom is a Nvidia GPU with Compute Capability 2.1 or higher. 
A list with Compute Capability versions and Nvidia GPU models can be found here https://en.wikipedia.org/wiki/CUDA

If you are looking for a used/new GPU, the price range is ~60$-600$. 
- If money is an issue, one of the cheapest and _oldest_ supported graphics cards would be the _GeForce GTX 460_ with 1GB, 384 Cuda cores and Compute Capability 2.1 from 2011. _However I would not go for such an old GPU if you don´t have to_. 
- For ~150$ one can get a still decent _NVIDIA GeForce GTX 1050Ti_  (released in 2016) with 4GB, 768 Cuda cores and Compute Capability 6.1 for example).

**Comment by hlyman** [comment] 2020-06-19 19:13
The driver in my PC is:  AMD Radeon HD 6450.

------ Original Message ------

**Comment by natowi** [comment] 2020-06-19 19:28
Ok, your AMD Radeon HD 6450 is from around 2011. It is relatively small, newer GPUs take up to two slots of space.

What CPU do you have and how much RAM? (Just checking if it makes sense to upgrade the GPU)

**Comment by hlyman** [comment] 2020-06-19 19:30
ERROR:

The card in  my pd is:  AMD Radeon HD 6450.

------ Original Message ------

**Comment by natowi** [comment] 2020-06-19 19:51
If you have 8 GB Ram installed in your computer (which was good in 2011), you may get problems when computing larger datasets (or may need to compromise with the reconstruction quality), 16GB would be better. Your CPU is probably still fine.

I think now you have all the information to look for suitable hardware.

**Comment by hlyman** [comment] 2020-06-19 19:52
PC has 16.0 GB.
Processoris:  AMD A10-7870K R7,12 Compute Cores 4C+8G


------ Original Message ------
From: "Hugh" <hlyman@comcast.net>
To: "alicevision/meshroom" 
<reply@reply.github.com>
Sent: 6/19/2020 12:30:15 PM
Subject: Re[2]: [alicevision/meshroom] [question] sensor database no 
edit permission (#943)

**Comment by hlyman** [comment] 2020-06-19 19:56
PC does have 16 GB of RAM

------ Original Message ------
From: "Hugh" <hlyman@comcast.net>
To: "alicevision/meshroom" 
<reply@reply.github.com>
Sent: 6/19/2020 12:52:29 PM
Subject: Re[3]: [alicevision/meshroom] [question] sensor database no 
edit permission (#943)

**Comment by natowi** [comment] 2020-06-19 20:05
Yes, that´s still decent hardware and worth upgrading the GPU.

**Comment by hlyman** [comment] 2020-06-19 20:17
OK can you tell which reasonably priced GPU to get?

------ Original Message ------

**Comment by natowi** [comment] 2020-06-19 20:25
I don´t know your PCIe version (the GPU socket) which restricts supported GPUs, also some newer GPUs require more power and more physical space. So there are many things to consider, that´s why I recommended you to ask someone local, who can take a look at your hardware.

**Comment by natowi** [comment] 2020-06-19 20:29
If your have PCIe3, enough power/cables and space, you can take a look at the GeForce GTX 1050 or GeForce GTX 1060.

**Comment by natowi** [comment] 2020-06-19 21:52
I close this issue as this is no longer Meshroom related and your questions were answered. All the best with your project and feel free to open a new Meshroom related issue if new questions/problems arise.

**Closed by natowi** 2020-06-19 21:52 UTC
Labels: type:question, windows

**Comment by hlyman** [comment] 2020-06-20 00:46
Thanks for help.  I got a Geforce 1050 installed am an now running a 
file.

------ Original Message ------
