### ISSUE TITLE
"Red bar error" at Depth Map

### ISSUE THREAD

**Issue by MrGuccu** [alicevision/meshroom#431] opened 2019-03-24 22:33 UTC
I have just downloaded Meshroom to start learning some photo scanning, but it seems like there is a problem. I took 143 pictures of a tree, and them imported them into Meshroom to make it into a model, but it stopped at depth map. Here is the log: 

[17:21:59.290059][info] Supported CUDA-Enabled GPU detected.
[17:21:59.490525][info] Found 1 image dimension(s): 
[17:21:59.490525][info] 	- [3648x2736]
[17:21:59.606185][info] Overall maximum dimension: [3648x2736]
[17:21:59.606185][info] Create depth maps.
number of CUDA devices:	1
   0: Quadro 4000
[17:21:59.607182][info] # GPU devices: 1, # CPU threads: 6
[17:21:59.608180][info] Plane sweeping parameters:
	- scale: 2
	- step: 3
[17:21:59.608180][info] PlaneSweepingCuda:
	- _nImgsInGPUAtTime: 2
	- scales: 2
	- subPixel: Yes
	- varianceWSH: 4
CUDA device no 0 for 0
Device 0 memory - used: 376.853119, free: 1671.146851, total: 2048.000000
Device 0 memory - used: 474.853119, free: 1573.146851, total: 2048.000000
[17:22:08.092464][info] Estimate depth map, view id: 34066621 

Here is the status:
"status": "ERROR",
    "execMode": "LOCAL",
    "nodeName": "DepthMap_1",
    "nodeType": "DepthMap",
    "packageName": "aliceVision",
    "packageVersion": null,
    "graph": "",
    "commandLine": "aliceVision_depthMapEstimation  --input \"C:/Users/Aron Szucs/Desktop/MeshroomCache/StructureFromMotion/68a151cdf289955ac79c7917ac5c1c3f2674b067/sfm.abc\" --imagesFolder \"C:/Users/Aron Szucs/Desktop/MeshroomCache/PrepareDenseScene/a9d1df3221755f9cbb1e813eaffaa11f89eb8243\" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output \"C:/Users/Aron Szucs/Desktop/MeshroomCache/DepthMap/0b4a38ac1d1c535b8ef7b3b0ef37102f98a1d4a8\" --rangeStart 0 --rangeSize 3",
    "env": null,
    "startDateTime": "2019-03-24 17:21:59.102516",
    "endDateTime": "2019-03-24 17:21:51.762801",
    "elapsedTime": 40.068347454071045,
    "hostname": "DESKTOP-VM57M68",
    "sessionUid": "9d10f512-4e7f-11e9-a384-144f8a102a0b",
    "returnCode": 3221226505,
    "elapsedTimeStr": "0:00:40.068347"

Is anyone else experiencing these issues, or just me? Any help would be great.
Thanks,
MrGuccu

**Comment by daktylus** [comment] 2019-03-28 12:51
There is an error with Meshroom 2019.1  Try the 2018 release. This works for most people

**Comment by hwkeyser** [comment] 2019-04-08 20:17
I had this same issue today. My project won't proceed past Depthmap for what appears to be the same error.

**Comment by JanWalterSluka** [comment] 2019-05-24 19:12
I am getting what seems to be the same issue. The project works fine when I use 2018 release, but the processing takes a lot longer on same settings than in 2019 release. I tried building current source (I read in another thread that the issue was fixed), but I am having trouble making all the dependencies work - I am not too experienced in building complicated applications. Is there any ETA on a new Meshroom release? I seen mid of May mentioned. If there is a new release coming soon, I probably ought to not bother trying to build it myself.

**Comment by simogasp** [comment] 2019-07-26 09:38
The problem could be fixed by alicevision/AliceVision/#671 which has been merged into the current develop of AliceVision. You can try to get the latest AliceVision develop branch as well as the latest develop of meshroom and see if the problem is fixed. There are no binaries yet available, they will be very soon with the 2019.2 release which is on the way in the next few days.

**Comment by bluetoaster** [comment] 2019-07-31 21:08
I did find out that when I lowered the resolution of the images that I used I stopped getting stuck at depth map so try lowering the resolution of your pictures.

**Closed** 2019-08-08 12:22 UTC
Labels: type:bug
