### ISSUE TITLE
[error]

### ISSUE THREAD

**Issue by IdontKnowWin10** [alicevision/meshroom#1038] opened 2020-08-17 15:46 UTC
Please help me with this error idk what to do here is the log:
Program called with the following parameters:
 * evCorrection = 0
 * input = "C:/Users/Datoranv�ndare/Pictures/Camera Roll/MeshroomCache/StructureFromMotion/60a185619ff8a0dd6ae6fcd26ad9dd31150bcdd1/sfm.abc"
 * output = "C:/Users/Datoranv�ndare/Pictures/Camera Roll/MeshroomCache/PrepareDenseScene/2321b94d1cd6dfa5b68b0411c49d706917a34017"
 * outputFileType = "exr"
 * rangeSize = 40
 * rangeStart = 0
 * saveMatricesTxtFiles = 0
 * saveMetadata = 1
 * verboseLevel = "info"

Exporting Scene Undistorted Images
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
[16:39:59.918187][info] median Ev : 10.438

**Comment by ChemicalXandco** [comment] 2020-08-17 16:36
duplicate of #1012,  #1015

**Comment by IdontKnowWin10** [comment] 2020-08-17 16:56
How do I fix it?

**Comment by ChemicalXandco** [comment] 2020-08-17 17:07
In the latest release there is a problem with how paths with non-ascii characters are parsed in the `PrepareDenseScene` node, to get around this you need to put your images somewhere where the path only contains ascii characters.

**Comment by IdontKnowWin10** [comment] 2020-08-17 17:15
Thanks for the Help

**Closed** 2020-08-18 06:29 UTC
Labels: bug
