### ISSUE TITLE
Errors after launch

### ISSUE THREAD

**Issue by yasha107** [alicevision/meshroom#770] opened 2020-01-26 01:24 UTC
I get the following errors in the Meshroom console after launching it:
```
[0x7FFB0C19C5B0] ANOMALY: meaningless REX prefix used
[0x7FFB0C19C5B0] ANOMALY: meaningless REX prefix used
```
And the program's UI becomes unresponsive after about a minute without any other errors in console

I got the binaries from the official website, version of Meshroom is 2019.2.0-win64

My specs:
i3 4170
2x 4GB 1333mhz DDR3
GTX 1050ti
No SSD, 2 HDDs
Windows 10 Home Edition 64 bit

**Comment by yasha107** [comment] 2020-01-26 01:26
Label of the issue should be bug, not sure how to change it though

**Comment by natowi** [comment] 2020-01-26 08:42
Antivirus software or Nvidia display software might be the cause, try disabling your antivirus software and updating to the latest nvidia drivers. Re-download the Meshroom binaries, download might have been incomplete.
Do you also get the error when opening the cli and typing _dir_?

However this bug does not seem to be Meshroom related: http://www.os2museum.com/wp/anomaly-meaningless-rex-prefix-used/

**Comment by yasha107** [comment] 2020-01-26 11:36
Got latest Nvidia Game Ready driver from GeForce Experience, got no antivirus, even Windows Defender is disabled.
If by CLI you mean Windows' CMD, no, I don't get that error.
Redownloaded binaries couple times already, even tried to downgrade to the 2018.1.0 version that I had before and worked fine, but that is broken too so yeah, probably not Meshroom related

**Comment by natowi** [comment] 2020-01-26 14:04
Check your previous driver and software installations, maybe the problem was introduced by a previous installation/update.

**Comment by natowi** [comment] 2020-01-26 14:49
I close this issue as this bug is likely not Meshroom related.

**Closed by natowi** 2020-01-26 14:49 UTC
Labels: bug
