### ISSUE TITLE
Meshroom 2021 1.0 with Iphone XR --> Failed to import [question]

### ISSUE THREAD

**Issue by Lammeur** [alicevision/Meshroom#1654] opened 2022-03-27 17:12 UTC
**Describe the problem**
Hi Everyone,

Today I wanted tried Meshroom but my photo didn't wanted to upload into the app...
And will not talk about how the stupid and annoying part of how to allow the access of your pictures into your iphone... 
It's worst when you have to remove all your devices connected to your account because Apple doesn't allow to permit 5 devices to access at your Iphone...

So, after few tries, I went check the allowed format that Meshroom allows and it doesn't allow iPhone's Pictures native format...
       --> Thanks to this Tuto, I choised the second way, to dowload HEIC Convert for convert my HEIC to JPG : 
https://blog.fonepaw.com/heif-heic-converter-win-mac.html

Normally it will should work ! But not...
I tried to upload all my pictures but it didn't worked, I tried so just one for see, it was working but it will be long to do one by one, then a tried to reupload everything and always the same issue...

![Corrupt](https://user-images.githubusercontent.com/80065348/160291796-0f9e69aa-f9ed-416c-a89f-4e1e217b9bda.PNG)

So I tried this another different picture which comes to a Canvas website and this one was working.

I even tried to restart the app and retried or even deleted the app and extract again the app to the archive...

I saw a Console log working and I fought an Error Code : 3221225477
I tried to find in google something close to my case, and I find this case : [https://github.com/alicevision/meshroom/issues/208]

Mostly that I understood, it can come to the dimension of my picture or something wrong into the source file or converted files...
![image](https://user-images.githubusercontent.com/80065348/160292671-a07fa36e-3616-4884-b7b2-34634b8f5ebb.png)

So my questions are : 
  - Someone see something that I missed ?
  - Should I cry and forget this experience ?
  - Someone has an advice ? ( I hope )
  - Should I redefine my picture ?
       -> If yes, I risk to lost data right ?
In any case, will try ! But I wanted to ask to the community before and try during waiting an miraculous answer x)
  - Someone had this issue before ?

Thanks for writing me, I hope I put enough information for help you to help me and my english is not too bad x)
Sorry, it's my first time that I used github, I tried to put the console log into a Code item but I didn't achieve...
// Beginning of the Console
`
"```"
Program called with the following parameters:
 * allowSingleView = 1
 * allowedCameraModels = "pinhole,radial1,radial3,brown,fisheye4,fisheye1"
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:\Users\THOMAS~1.BEC\AppData\Local\Temp\tmpqo_gs1pc/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"
 * output = "C:/Users/THOMAS~1.BEC/AppData/Local/Temp/tmpqo_gs1pc/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm"
 * sensorDatabase = "C:\Users\thomas\Documents\Perso\OpenSource\Meshroom-2021.1.0\aliceVision\share\aliceVision\cameraSensors.db"
 * useInternalWhiteBalance = 1
 * verboseLevel = "info"
 * viewIdMethod =  Unknown Type "enum aliceVision::sfmDataIO::EViewIdMethod"
 * viewIdRegex = ".*?(\d+)" (default)

ERROR:root:Error while building intrinsics: CameraInit failed with error code 3221225477.
Command was: "aliceVision_cameraInit  --sensorDatabase "C:\Users\thomas\Documents\Perso\OpenSource\Meshroom-2021.1.0\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1 --useInternalWhiteBalance True --viewIdMethod metadata --verboseLevel info --output "C:/Users/THOMAS~1.BEC/AppData/Local/Temp/tmpqo_gs1pc/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm" --allowSingleView 1 --input "C:\Users\THOMAS~1.BEC\AppData\Local\Temp\tmpqo_gs1pc/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"".

WARNING:root:QQmlComponent: Created graphical object was not placed in the graphics scene.
Program called with the following parameters:
 * allowSingleView = 1
 * allowedCameraModels = "pinhole,radial1,radial3,brown,fisheye4,fisheye1"
 * defaultCameraModel = "" (default)
 * defaultFieldOfView = 45
 * defaultFocalLengthPix = -1 (default)
 * defaultIntrinsic = "" (default)
 * groupCameraFallback =  Unknown Type "enum EGroupCameraFallback"
 * imageFolder = "" (default)
 * input = "C:\Users\THOMAS~1.BEC\AppData\Local\Temp\tmpjuuz8xsl/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"
 * output = "C:/Users/THOMAS~1.BEC/AppData/Local/Temp/tmpjuuz8xsl/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm"
 * sensorDatabase = "C:\Users\thomas\Documents\Perso\OpenSource\Meshroom-2021.1.0\aliceVision\share\aliceVision\cameraSensors.db"
 * useInternalWhiteBalance = 1
 * verboseLevel = "info"
 * viewIdMethod =  Unknown Type "enum aliceVision::sfmDataIO::EViewIdMethod"
 * viewIdRegex = ".*?(\d+)" (default)

ERROR:root:Error while building intrinsics: CameraInit failed with error code 3221225477.
Command was: "aliceVision_cameraInit  --sensorDatabase "C:\Users\thomas\Documents\Perso\OpenSource\Meshroom-2021.1.0\aliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1 --useInternalWhiteBalance True --viewIdMethod metadata --verboseLevel info --output "C:/Users/THOMAS~1.BEC/AppData/Local/Temp/tmpjuuz8xsl/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm" --allowSingleView 1 --input "C:\Users\THOMAS~1.BEC\AppData\Local\Temp\tmpjuuz8xsl/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"".

WARNING:root:QQmlComponent: Created graphical object was not placed in the graphics scene.
"```"
`

**Comment by Lammeur** [comment] 2022-03-27 17:39
I forget my laptop is a Dell Latitute E5570 with W10 version 20H2

**Comment by natowi** [comment] 2022-03-27 18:49
During the conversion from heic to jpeg there are probably some issues introduced in the file structure by the conversion software. You can check the jpeg for [errors](https://github.com/alicevision/meshroom/issues/208#issuecomment-429572685) or share a sample image for testing.

**Comment by Lammeur** [comment] 2022-03-27 22:24
> During the conversion from heic to jpeg there are probably some issues introduced in the file structure by the conversion software. You can check the jpeg for [errors](https://github.com/alicevision/meshroom/issues/208#issuecomment-429572685). I can recommend you to bulk convert your heic files to jpeg using irfran view batch convert.
>  
> Internally Meshroom uses the oiio library to read images, and some issues with the heic format were present, when the last Meshroom version was released [OpenImageIO/oiio#2794](https://github.com/OpenImageIO/oiio/issues/2794) . I was able to reproduce your issue with the sample data provided in # 2794. In the next release, Meshroom will use a more recent version of oiio, so heic will be supported as well.

Thanks, I will check tomorrow about the iPhone's picture part !

Also I have another question,
My girlfriend brought her job's camera, I did shots for try with "normal" JPG.
Meshroom uploaded everything well, so I started the compilation and I had a Cuda Error...

 My laptop doesn't have a NVIDIA GPU, sadly there is an issue with that...
Is it possible to do the same job without an NVIDIA GPU ?

I thought this into thanks to google : [https://github.com/openphotogrammetry/meshroomcl](url)
I tried with the same shots but the picture compilation never achieved...
What do you think about this behavior ?

**Comment by Lammeur** [comment] 2022-03-27 22:26
Ah sorry for the second part !
I restarted Meshroom CL, I tried just one and the picture uploaded !!

Let's see if the compilation finish !!

**Comment by Lammeur** [comment] 2022-03-28 08:18
> During the conversion from heic to jpeg there are probably some issues introduced in the file structure by the conversion software. You can check the jpeg for [errors](https://github.com/alicevision/meshroom/issues/208#issuecomment-429572685). I can recommend you to bulk convert your heic files to jpeg using irfran view batch convert.
> 
So I tried to scan the file with Bad Peggy, you will find the result here : 
![0xdb error](https://user-images.githubusercontent.com/80065348/160355418-58dda2ce-51d3-457c-b57f-7a95ad7d005a.PNG)
Do you have an idea about this issue ?

Also I tried Irfran for convert the HEIC file, bad result too...
![Batch irFran](https://user-images.githubusercontent.com/80065348/160355882-7920e0d8-a823-478d-a416-1b6ce714e41c.PNG)

> Internally Meshroom uses the oiio library to read images, and some issues with the heic format were present, when the last Meshroom version was released [OpenImageIO/oiio#2794](https://github.com/OpenImageIO/oiio/issues/2794) . I was able to reproduce your issue with the sample data provided in # 2794. In the next release, Meshroom will use a more recent version of oiio, so heic will be supported as well.
So I should wait the new release ?..

**Comment by natowi** [comment] 2022-03-29 21:28
1) Yes, that is the error message I expected. This is likely caused by non-standard metadata fields within the JPEG.

2) Sorry I already installed the required codec some time ago, but I don´t recall where it came from.
You need to find a good conversion tool for your heic files, that only transfers standard metadata fields or removes them all (and you manually need to specify the settings in the camera init node.

I don´t know when the next version will be released, so finding a suitable tool to convert your images will be faster :)

**Comment by Lammeur** [comment] 2022-04-07 15:35
> 1. Yes, that is the error message I expected. This is likely caused by non-standard metadata fields within the JPEG.
> 2. Sorry I already installed the required codec some time ago, but I don´t recall where it came from.
>    You need to find a good conversion tool for your heic files, that only transfers standard metadata fields or removes them all (and you manually need to specify the settings in the camera init node).
>    This small tool does the conversion without issues, but removes all the metadata: [heif-convert.exe (CLI tool) ](https://github.com/pphh77/libheif-Windowsbinary/releases/download/v1.12.0/libheif-1.12.0-r1638-g8f8035a-win64.7z) using the ExifTool by Phil Harvey you can reattach the metadata. Or better: find a good tool that does all that (my quick search did not turn up much)
> 
> I don´t know when the next version will be released, so finding a suitable tool to convert your images will be faster :)
> 
> If possible choose another format than heic to capture your images for the moment

Thanks to you answer, I try with a real camera but the issue now is how to process in CPU mode ?
Because I don't have the NVIDIA GPU...

**Comment by natowi** [comment] 2022-04-08 18:19
See https://github.com/alicevision/meshroom/wiki/Draft-Meshing

**Comment by Onlyshelton** [comment] 2023-12-30 20:29
I receive the following error in MeshroomCL. I took my photos with a canon rebel t3, and all the file types are jpg. What should I do in order to get the pictures to mesh?

![Capture](https://github.com/alicevision/Meshroom/assets/155263746/4ef9973a-c1bc-4aec-bab7-bf7f5e0a7460)

**Comment by natowi** [comment] 2024-01-02 13:30
This issue may be resolved in a newer official Meshroom Version. MeshroomCL is still based on the old release and we are not related to the project.

**Comment by natowi** [comment] 2024-01-02 13:33
The issue should be resolved with the latest 2023 release. Feel free to open a new issue if you still encounter a problem importing HEIC files.

**Closed by natowi** 2024-01-02 13:33 UTC
Labels: type:question

**Comment by Onlyshelton** [comment] 2024-01-02 17:52
Will I need a cuda nvidia to run Meshroom? I downloaded MeshroomCL because
it did not require one.

**Comment by natowi** [comment] 2024-01-02 19:49
@Onlyshelton https://github.com/alicevision/Meshroom/wiki/Draft-Meshing

**Comment by Onlyshelton** [comment] 2024-01-05 19:45
Please see the image below and attach logo status text insert. My screen
has been stuck on this same page for over 10 min and the status has
not changed. What should I do to fix this?


[13:25:49.612936][info] loadPairs: image pair (249473424, 2145254390) added.

[13:25:49.612936][info] Number of pairs: 2950

[13:25:49.613937][info] There are 158 views and 2950 image pairs.

[13:25:49.613937][info] Load features and descriptors

Loading regions

0%   10   20   30   40   50   60   70   80   90   100%

|----|----|----|----|----|----|----|----|----|----|

***************************************************

[13:26:01.472799][info] Putative matches (unknown poses): 2950 image pairs.

[13:26:01.472799][info] dspsift Regions Matching



0%   10   20   30   40   50   60   70   80   90   100%

|----|----|----|----|----|----|----|----|----|----|
