### ISSUE TITLE
GCP support

### ISSUE THREAD

**Issue by falu** [alicevision/meshroom#230] opened 2018-09-01 19:48 UTC
Any plans for support GCP-s (Ground Control Points) to fit model to world or local coordinate systems?

**Comment by ChemicalXandco** [comment] 2018-09-01 20:28
Duplicate of [alicevision/AliceVision#402](https://github.com/alicevision/AliceVision/issues/402): it has thumbs ups including @fabiencastan so yes there are plans

**Comment by simogasp** [comment] 2019-08-17 08:44
See #402

**Closed by simogasp** 2019-08-17 08:44 UTC
Labels: type:enhancement
