### ISSUE TITLE
DepthMap trouble

### ISSUE THREAD

**Issue by HoneyShmily** [alicevision/meshroom#504] opened 2019-06-11 13:22 UTC
I met this problem when I used the command line. The version is 2019.1 and the error is:

 [7/12](1/13) DepthMap
 - commandLine: aliceVision_depthMapEstimation  --input "C:/Users/Aymdr/AppData/Local/Temp/MeshroomCache/StructureFromMotion/d444f20fbae0d09b859bfaae0c0fcc87f3a8a275/sfm.abc" --imagesFolder "C:/Users/Aymdr/AppData/Local/Temp/MeshroomCache/PrepareDenseScene/670e191bb940770d677a42c5743651f241026a5c" --downscale 2 --minViewAngle 2.0 --maxViewAngle 70.0 --sgmMaxTCams 10 --sgmWSH 4 --sgmGammaC 5.5 --sgmGammaP 8.0 --refineMaxTCams 6 --refineNSamplesHalf 150 --refineNDepthsToRefine 31 --refineNiters 100 --refineWSH 3 --refineSigma 15 --refineGammaC 15.5 --refineGammaP 8.0 --refineUseTcOrRcPixSize False --exportIntermediateResults False --nbGPUs 0 --verboseLevel info --output "C:/Users/Aymdr/AppData/Local/Temp/MeshroomCache/DepthMap/ad372c6a05b73a14a4c110f7b7bf02e9bfbdf7a5" --rangeStart 0 --rangeSize 3
 - logFile: C:/Users/Aymdr/AppData/Local/Temp/MeshroomCache/DepthMap/ad372c6a05b73a14a4c110f7b7bf02e9bfbdf7a5/0.log
 - elapsed time: 0:00:00.685612
[2019-06-11 20:55:33,453][ERROR] Error on node computation: Error on node "DepthMap_1(0)":
Log:

WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(10)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(11)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(12)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Publish_1" from Status.SUBMITTED to Status.NONE
Traceback (most recent call last):
  File "bin/meshroom_photogrammetry", line 137, in <module>
    meshroom.core.graph.executeGraph(graph, toNodes=toNodes, forceCompute=args.forceCompute, forceStatus=args.forceStatus)
  File "F:\project\meshroom\meshroom\core\graph.py", line 1131, in executeGraph
    chunk.process(forceCompute)
  File "F:\project\meshroom\meshroom\core\node.py", line 271, in process
    self.node.nodeDesc.processChunk(self)
  File "F:\project\meshroom\meshroom\core\desc.py", line 452, in processChunk
    raise RuntimeError('Error on node "{}":\nLog:\n{}'.format(chunk.name, logContent))
RuntimeError: Error on node "DepthMap_1(0)":
Log:

I have check the issue before but do not solve it. how can I??

**Comment by fabiencastan** [comment] 2019-06-11 13:28
Would be good to see the log file (with verbose in "trace") to get more information.

**Comment by HoneyShmily** [comment] 2019-06-11 13:39
sorry, but the logfile in MeshroomCache in DepthMap is empty.

**Comment by qiu109** [comment] 2019-07-19 09:05
has the problem solved? I have the same problem.

**Comment by skinkie** [comment] 2019-07-21 13:30
We can reproduce this with the dev build of @natowi. But the release of 2019.1 works without an issue.

**Comment by simogasp** [comment] 2019-07-26 09:40
The problem could be fixed by alicevision/AliceVision#671 which has been merged into the current develop of AliceVision. You can try to get the latest AliceVision develop branch as well as the latest develop of meshroom and see if the problem is fixed. There are no binaries yet available, they will be very soon with the 2019.2 release which is on the way in the next few days.

**Closed** 2019-08-08 12:22 UTC
Labels: type:bug
