### ISSUE TITLE
Difference between RAW dense point cloud and normal[question]

### ISSUE THREAD

**Issue by miquelrosell99** [alicevision/meshroom#889] opened 2020-05-10 17:03 UTC
As it says in the title, what is the difference between the RAW point cloud and the dense point cloud? I can't find any info in the documentation. The RAW one has more points but more noise, or something like that? To better understand what to use in each case
Thanks!

**Comment by natowi** [comment] 2020-06-21 06:45
Duplicate of https://github.com/alicevision/meshroom/issues/888

**Closed by natowi** 2020-06-21 06:45 UTC
Labels: type:question
