### ISSUE TITLE
Feature Request: Masking Tool like in Agisoft’s Photoscan

### ISSUE THREAD

**Issue by Neelix96** [alicevision/meshroom#270] opened 2018-10-12 10:37 UTC
Would help for scanning every angle of an object.
Found a tutorial von Photoscan:
https://bertrand-benoit.com/blog/the-poor-mans-guide-to-photogrammetry/

**Comment by Powerbyte7** [comment] 2018-10-12 14:36
Duplicate of #188

**Closed** 2019-06-28 15:21 UTC
