### ISSUE TITLE
Add different computing steps to the meshing node[request]

### ISSUE THREAD

**Issue by miquelrosell99** [alicevision/meshroom#904] opened 2020-05-20 07:57 UTC
Could you please add different steps to the meshing node, similar to the DepthMap node and all the others, so we don't have to recompute it all over again if the program or the pc crashes?
Once it generates the RAW point cloud for example, or at each filtering step.
It would be a nice feature to have.

On a side note, having a "pause" button would be really good too, so we can use the PC for other things if we need too, and then we can resume the computation.

Thanks a ton

**Comment by natowi** [comment] 2020-05-20 10:17
Reference: https://github.com/alicevision/meshroom/issues/798

**Comment by miquelrosell99** [comment] 2020-05-22 08:40
> Reference: #798

It's not possible for meshing node

**Comment by natowi** [comment] 2020-06-21 06:44
Duplicate of https://github.com/alicevision/meshroom/issues/888

**Closed by natowi** 2020-06-21 06:44 UTC
Labels: feature request
