### ISSUE TITLE
Meshroom pins GPU and 1 core to 100%

### ISSUE THREAD

**Issue by baldyman01** [alicevision/meshroom#554] opened 2019-07-14 18:23 UTC
Dell M3800, i7, Quadro K1100M 

Linux Mint 19  - 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

On Meshroom 2019-1-0. Simply starting the program pins my GPU and one of my cores to 100% utilization.

![Screenshot from 2019-07-14 19-20-46](https://user-images.githubusercontent.com/33987743/61187714-bc756600-a66c-11e9-868a-2717c5811b21.png)

**Comment by ChemicalXandco** [comment] 2019-07-30 08:33
Duplicate of #336

**Closed** 2019-07-30 08:58 UTC
Labels: linux
