### ISSUE TITLE
Depth Map failure

### ISSUE THREAD

**Issue by bucktheduck** [alicevision/meshroom#425] opened 2019-03-21 02:11 UTC
Hi everybody! Newish to Photogrammetry, and I love the potential in this software! It keeps "red bar" failing in the DepthMap step. Attached is my log. I'm running on a GTX750 ti
[Depthfail.txt](https://github.com/alicevision/meshroom/files/2990663/Depthfail.txt)

Thanks for any tips!

**Comment by hargrovecompany** [comment] 2019-03-21 06:42
I'm by no means an expert but i've had red bar fails....usually it was because i simply didn't have enough images with enough clarity and overlap.

**Comment by daktylus** [comment] 2019-03-28 13:12
Are you using the release 2019.1

There is an error with Meshroom 2019.1 Try the 2018 release. This works for most people

See: https://github.com/alicevision/meshroom/issues/409#issuecomment-475881859

**Comment by simogasp** [comment] 2019-07-26 09:37
The problem could be fixed by alicevision/AliceVision/#671 which has been merged into the current develop of AliceVision. You can try to get the latest AliceVision develop branch as well as the latest develop of meshroom and see if the problem is fixed. There are no binaries yet available, they will be very soon with the 2019.2 release which is on the way in the next few days.

**Closed** 2019-08-08 12:22 UTC
Labels: type:bug
