### ISSUE TITLE
Error during Graph execution Error on node "PrepareDenseScene_1":

### ISSUE THREAD

**Issue by JakubkrizAldaGames** [alicevision/meshroom#235] opened 2018-09-05 12:02 UTC
My process gets to prepare dense scene but after that it just fails for some reason 16gb ram gtx 1060

WARNING: downgrade status on node "CameraConnection_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(4)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(5)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(6)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(7)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(8)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(9)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(10)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(11)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMap_1(12)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(0)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(1)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(2)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "DepthMapFilter_1(3)" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Meshing_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "MeshFiltering_1" from Status.SUBMITTED to Status.NONE
WARNING: downgrade status on node "Texturing_1" from Status.SUBMITTED to Status.NONE
ERROR:root:Error during Graph execution Error on node "PrepareDenseScene_1":
Log:
Program called with the following parameters:
 * input = "C:/Users/J/Desktop/Nová složka/3/MeshroomCache/StructureFromMotion/9185b7853e8a173f2610fd31238fa7437c75a394/sfm.abc"
 * output = "C:/Users/J/Desktop/Nová složka/3/MeshroomCache/PrepareDenseScene/14a44dc18047f484b2e27e2bd35f804e64ce2a73"
 * verboseLevel = "info"

Exporting Scene Data
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|

**Comment by yann-lty** [comment] 2018-09-05 16:01
Duplicate of #209: you have non ASCII characters in your project path and the PrepareDenseScene step fails.
Closing this one to avoid multiple issues on the same subject.

**Closed by yann-lty** 2018-09-05 16:01 UTC

**Comment by JakubkrizAldaGames** [comment] 2018-09-05 19:31
thanks I dindnt think of that. I renamed the folders and it works now guess installing windows in your native language isnt really a good idea haha thanks again you saved me :)

**Comment by nexorium** [comment] 2019-01-29 13:08
Thank you @JakubkrizAldaGames. I didn't know how to fix it, I thought it was first my pics that weren't good enough. That would be great if they can fix that and make it compatible for national machines. Thanks
