### ISSUE TITLE
Texturing node issues in Meshroom v2020.1.0

### ISSUE THREAD

**Issue by ziiler** [alicevision/meshroom#1255] opened 2021-02-06 10:24 UTC
Hello,

I am trying to run a reconstruction in v 2020.1.0 but I am getting an error in the Texturing node, the exact same reconstruction terminates successfully in v 2019.2.0, I have included the log from the texture node for both versions. 
The same default pipeline is used in both cases, with the following changes:
- Texture node attributes: 
--file type: jpg
--Unwrap Method: LSCM
- The number of faces is reduced to <= 600k by using MeshDecimate after the Meshing node instead of MeshFiltering

In v 2020.1.0 the reconstruction with unwrap method set to Basic works. For my project I use different levels of detail and cut the meshes into tiles. Since I end-up with a large amount of tiles and the goal is to have each tile < 100 kB texture file size is an issue.
Images : 302 , 4000x3000 pixels

#### v2020.1.0 - Log output from Texture node:

Program called with the following parameters:
 * angleHardThreshold = 90
 * bestScoreThreshold = 0.1
 * correctEV = 0
 * downscale =  Unknown Type "j"
 * fillHoles = 0
 * flipNormals = 0
 * forceVisibleByAllVertices = 0
 * imagesFolder = "/run/media/carl/dataLinux3/debugMeshroom2020/MeshroomCache/PrepareDenseScene/bc5e491f8fb41e7fc25ff7e6d30096229c41978b"
 * input = "/run/media/carl/dataLinux3/debugMeshroom2020/MeshroomCache/Meshing/ac3f7045628287cd3a64f94a69d7180bdb6d1538/densePointCloud.abc"
 * inputMesh = "/run/media/carl/dataLinux3/debugMeshroom2020/MeshroomCache/MeshDecimate/009621b15a9ea3d122636a54d2cfa5504c61cea9/mesh.obj"
 * multiBandDownscale =  Unknown Type "j"
 * multiBandNbContrib =  Unknown Type "St6vectorIiSaIiEE"
 * output = "/run/media/carl/dataLinux3/debugMeshroom2020/MeshroomCache/Texturing/809cb359c95fcb96b92d7f703fe74213a61d73fb"
 * outputTextureFileType = "jpg"
 * padding =  Unknown Type "j"
 * processColorspace = "sRGB"
 * subdivisionTargetRatio = 0.8
 * textureSide =  Unknown Type "j"
 * unwrapMethod = "LSCM"
 * useScore = 1
 * useUDIM = 1
 * verboseLevel = "info"
 * visibilityRemappingMethod = "PullPush"

[09:04:01.496778][info] Load dense point cloud.
[09:04:02.143077][warning] Alembic LOAD: NO OBSERVATIONS_WITH_FEATURES: , mvg_visibilityFeatId: 0, mvg_visibilityFeatPos: 0, OBSERVATIONS_WITH_FEATURES flag: false
[09:04:06.309775][info] Found 1 image dimension(s): 
[09:04:06.309816][info] 	- [4000x3000]
[09:04:06.493617][info] Overall maximum dimension: [4000x3000]
[09:04:06.493664][info] Load input mesh.
[09:04:06.493678][info] Loading mesh from obj file: /run/media/carl/dataLinux3/debugMeshroom2020/MeshroomCache/MeshDecimate/009621b15a9ea3d122636a54d2cfa5504c61cea9/mesh.obj
[09:04:06.546644][info] 	- # vertices: 153568
	- # normals: 0
	- # uv coordinates: 0
	- # triangles: 306325
[09:04:06.767194][info] Mesh loaded: 
	- #points: 153568
	- # triangles: 306325
[09:04:06.768069][info] Convert dense point cloud into ref mesh
[09:04:10.243955][info] remapMeshVisibility based on triangles start.
[09:04:22.135212][info] remapMeshVisibility done.
[09:04:22.137244][info] Input mesh has no UV coordinates, start unwrapping (LSCM)
[09:04:22.155636][info] Start mesh atlasing (using Geogram LSCM).
[09:08:49.531196][info] Mesh atlasing done.
Abnormal program termination: received signal 11 (Segmentation fault)

#### v2019.2.0 - Log output from Texture node:

Program called with the following parameters:
 * angleHardThreshold = 90
 * bestScoreThreshold = 0.1
 * correctEV = 0
 * downscale =  Unknown Type "j"
 * fillHoles = 0
 * flipNormals = 0
 * forceVisibleByAllVertices = 0
 * imagesFolder = "/run/media/carl/dataLinux3/debugMeshroom2020/MeshroomCache/PrepareDenseScene/a215fc890eecfa6c504df60b4e4cb166f4a711e8"
 * input = "/run/media/carl/dataLinux3/debugMeshroom2020/MeshroomCache/Meshing/9e6b67b145b2210c13518e28c952e58a59efcd01/densePointCloud.abc"
 * inputMesh = "/run/media/carl/dataLinux3/debugMeshroom2020/MeshroomCache/MeshDecimate/597a4e8c5784ee4a089ed21606b84f15afd33bad/mesh.obj"
 * multiBandDownscale =  Unknown Type "j"
 * multiBandNbContrib =  Unknown Type "St6vectorIiSaIiEE"
 * output = "/run/media/carl/dataLinux3/debugMeshroom2020/MeshroomCache/Texturing/890181cb6ef17f4f417c3a265e00396034722621"
 * outputTextureFileType = "jpg"
 * padding =  Unknown Type "j"
 * processColorspace = "sRGB"
 * textureSide =  Unknown Type "j"
 * unwrapMethod = "LSCM"
 * useScore = 1
 * useUDIM = 1
 * verboseLevel = "info"
 * visibilityRemappingMethod = "PullPush"

[10:49:00.141702][info] Found 1 image dimension(s): 
[10:49:00.141819][info] 	- [4000x3000]
[10:49:00.667181][info] Overall maximum dimension: [4000x3000]
[10:49:00.667226][info] Loading mesh from obj file: /run/media/carl/dataLinux3/debugMeshroom2020/MeshroomCache/MeshDecimate/597a4e8c5784ee4a089ed21606b84f15afd33bad/mesh.obj
[10:49:00.721854][info] 	- # vertices: 183257
	- # normals: 0
	- # uv coordinates: 0
	- # triangles: 365843
[10:49:00.972742][info] Mesh loaded: 
	- #points: 183257
	- # triangles: 365843
[10:49:03.494861][info] remapMeshVisibility based on triangles start.
[10:49:08.718815][info] remapMeshVisibility done.
[10:49:08.989253][info] Input mesh has no UV coordinates, start unwrapping (LSCM)
[10:49:09.009577][info] Start mesh atlasing (using Geogram LSCM).
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
...
OpenNL error in nlEigenSolve_ARPACK(): Could not factorize matrix
[10:51:40.364484][info] Mesh atlasing done.
[10:51:41.222819][info] Loading mesh from obj file: /tmp/87a7-3113-9d54-82d3.obj
[10:51:41.306098][info] 	- # vertices: 183257
	- # normals: 0
	- # uv coordinates: 242375
	- # triangles: 365843
[10:51:41.712449][info] Mesh loaded: 
	- #points: 183257
	- # triangles: 365843
[10:51:41.767000][info] remapMeshVisibility based on triangles start.
[10:51:42.487119][info] remapMeshVisibility done.
[10:51:42.517088][info] Unwrapping done.
[10:51:42.517127][info] Writing obj and mtl file.
[10:51:42.841001][info] Writing done: 
	- obj file: /run/media/carl/dataLinux3/debugMeshroom2020/MeshroomCache/Texturing/890181cb6ef17f4f417c3a265e00396034722621/texturedMesh.obj
	- mtl file: /run/media/carl/dataLinux3/debugMeshroom2020/MeshroomCache/Texturing/890181cb6ef17f4f417c3a265e00396034722621/texturedMesh.mtl
[10:51:42.841032][info] Generate textures.
[10:51:42.841038][info] Texturing: Use multiband blending with the following contributions per band:
[10:51:42.841042][info]   - 1
[10:51:42.841046][info]   - 5
[10:51:42.841049][info]   - 10
[10:51:42.841052][info] Texturing in sRGB colorspace.
[10:51:42.841102][info] Images loaded from cache with: no exposure correction
[10:51:42.841121][info] Total amount of free RAM  : 6849 MB.
[10:51:42.841124][info] Total amount of memory available : 6164 MB.
[10:51:42.841127][info] Total amount of an image in memory  : 137 MB.
[10:51:42.841134][info] Total amount of an atlas pyramid in memory: 3072 MB.
[10:51:42.841138][info] Processing 1 atlases by chunks of 1
[10:51:42.841144][info] Generating texture for atlases 1 to 1
[10:51:42.841150][info] Generating texture for atlas 1/1 (365843 triangles).
[10:51:48.240490][info] Reading pixel color.
[10:51:48.859893][info] - camera 17674289 (1/293) with contributions to 1 texture files:
[10:51:49.754479][info]   - Texture file: 1
[10:51:49.754527][info]       - band 1: 620 triangles.
[10:51:49.759454][info]       - band 2: 5476 triangles.
[10:51:49.763174][info]       - band 3: 13577 triangles.
...
[10:56:26.145043][info] Create texture 1
[10:56:26.145060][info]   - Computing final (average) color.
[10:56:26.616155][info]   - Edge padding (15 pixels).
[10:56:27.045596][info]   - Writing texture file: /run/media/carl/dataLinux3/debugMeshroom2020/MeshroomCache/Texturing/890181cb6ef17f4f417c3a265e00396034722621/texture_1001.jpg
[10:56:28.922208][info] Task done in (s): 455.185000

Machine details: Fedora 33, 32GB RAM, RAYZEN 9 3900X, RTX 2060 super

Any ideas?
Thanks
ziler

**Comment by ChemicalXandco** [comment] 2021-02-06 11:29
This is a duplicate of #1107. It will be fixed in the next release.

**Comment by natowi** [comment] 2021-02-26 22:51
The new release is now available

**Closed** 2021-02-26 22:52 UTC
Labels: bug

**Comment by kisakata** [comment] 2021-03-02 01:41
Hi,
I have tried creating a texture in Meshroom 2021.1.0,
but I am still getting the same error.

Here is an output of a log:


```
Program called with the following parameters:
 * angleHardThreshold = 90
 * bestScoreThreshold = 0.1
 * correctEV = 0
 * downscale =  Unknown Type "j"
 * fillHoles = 0
 * flipNormals = 0
 * forceVisibleByAllVertices = 0
 * imagesFolder = "/path/to/MeshroomCache/PrepareDenseScene/7d70ebe2ff827e7d052fda13125905262e26efe8"
 * input = "/path/to/MeshroomCache/Meshing/5b2eabfdfb55e7b2f93b342867d52bd9067108f4/densePointCloud.abc"
 * inputMesh = "/path/to/MeshroomCache/MeshFiltering/01afd69c15b35dc524675c009e1cc2cb0e734d40/mesh.obj"
 * multiBandDownscale =  Unknown Type "j"
 * multiBandNbContrib =  Unknown Type "St6vectorIiSaIiEE"
 * output = "/path/to/MeshroomCache/Texturing/34f89548f4ffccdbc2ab1edb99844a5132399887"
 * outputTextureFileType = "png"
 * padding =  Unknown Type "j"
 * processColorspace = "sRGB"
 * subdivisionTargetRatio = 0.8
 * textureSide =  Unknown Type "j"
 * unwrapMethod = "LSCM"
 * useScore = 1
 * useUDIM = 1
 * verboseLevel = "info"
 * visibilityRemappingMethod = "PullPush"

[14:20:15.738699][info] Load dense point cloud.
[14:20:15.801026][warning] Alembic LOAD: NO OBSERVATIONS_WITH_FEATURES: , mvg_visibilityFeatId: 0, mvg_visibilityFeatPos: 0, OBSERVATIONS_WITH_FEATURES flag: false
[14:20:16.098596][info] Found 1 image dimension(s): 
[14:20:16.098650][info] 	- [2348x1566]
[14:20:16.327848][info] Overall maximum dimension: [2348x1566]
[14:20:16.328390][info] Load input mesh.
[14:20:16.328414][info] Loading mesh from obj file: /path/to/MeshroomCache/MeshFiltering/01afd69c15b35dc524675c009e1cc2cb0e734d40/mesh.obj
[14:20:16.372089][info] 	- # vertices: 89097
	- # normals: 0
	- # uv coordinates: 0
	- # triangles: 177096
[14:20:16.536524][info] Mesh loaded: 
	- #points: 89097
	- # triangles: 177096
[14:20:16.537770][info] Convert dense point cloud into ref mesh
[14:20:16.660829][info] remapMeshVisibility based on triangles start.
[14:20:17.088824][info] remapMeshVisibility done.
[14:20:17.092473][info] Input mesh has no UV coordinates, start unwrapping (LSCM)
[14:20:17.107037][info] Start mesh atlasing (using Geogram LSCM).
Abnormal program termination: received signal 11 (Segmentation fault)
```

I've looked at the source code and it looks like it's seg faulting inside `geogram`'s [chart_scaling](https://github.com/alicevision/geogram/blob/8b2ae6148c7ab1564fa2700673b4275296ce80d3/src/lib/geogram/parameterization/mesh_param_validator.cpp#L152) function.

I don't know why but the my input has a mesh with a single facet which area/area2d of 0,
so `facet_scaling` is a empty list, and it crashes when it tries to access a last item on the list [here](https://github.com/alicevision/geogram/blob/8b2ae6148c7ab1564fa2700673b4275296ce80d3/src/lib/geogram/parameterization/mesh_param_validator.cpp#L190).

If I entered results of Meshing to the Texturing node, it works fine,
so it looks like MeshFiltering node is producing a mesh that is incomaptible.
Is there a recommended parameters for MeshFiltering?

**Comment by fabiencastan** [comment] 2021-03-02 09:45
You are probably running out of RAM. Look at the statistics tab on the Texturing node to check if the problem comes from RAM as I suspect.
You should keep the default unwrap method. As explained in the tooltip info, use the other unwrap methods **only** for texturing on lower resolution meshes after simplification or retopology.

**Comment by natowi** [comment] 2021-03-02 18:46
You can check the ram usage in the Statistics tab of the node (scroll down)

**Comment by kisakata** [comment] 2021-03-02 22:31
@fabiencastan, @natowi 
Thank you for the quick answers.

I have checked the memory usage.
It said that RAM Max Peak was 47G,
but it's less than 50% of total memory.
(my machine has 128G of memory)

I wanted to use "LSCM" method, so that I will get only one texture.
If default unwrap method ("Basic") is a recommended setting, I'll try to use that instead.

**Comment by davidbrodrick** [comment] 2021-11-11 02:56
I also get this problem with 2021.1.0 and the development version using LCSM or ABF. I've tried decimating the mesh to <20k triangles. I don't see anything to suggest it is running our of RAM.

```
Thread 1 "aliceVision_tex" received signal SIGSEGV, Segmentation fault.
0x00007ffff7b3c31b in GEO::ParamValidator::chart_scaling(GEO::Chart&) () from /DATADISK/projects/repos/AliceVision3/install/bin/../lib/libgeogram.so.1
(gdb) bt
#0  0x00007ffff7b3c31b in GEO::ParamValidator::chart_scaling(GEO::Chart&) () from /DATADISK/projects/repos/AliceVision3/install/bin/../lib/libgeogram.so.1
#1  0x00007ffff7b3cc8e in GEO::ParamValidator::chart_is_valid(GEO::Chart&) () from /DATADISK/projects/repos/AliceVision3/install/bin/../lib/libgeogram.so.1
#2  0x00007ffff7b2643b in GEO::mesh_make_atlas(GEO::Mesh&, double, GEO::ChartParameterizer, GEO::ChartPacker, bool) () from /DATADISK/projects/repos/AliceVision3/install/bin/../lib/libgeogram.so.1
#3  0x00007ffff7f969bd in aliceVision::mesh::Texturing::unwrap(aliceVision::mvsUtils::MultiViewParams&, aliceVision::mesh::EUnwrapMethod) ()
   from /DATADISK/projects/repos/AliceVision3/install/bin/../lib/libaliceVision_mesh.so.2
#4  0x000055555556c60a in aliceVision_main(int, char**) ()
#5  0x0000555555568973 in main ()

```

**Comment by ziiler** [comment] 2021-12-23 09:00
Hey, I finally got the texturing to work in version v2021, the trick is not to use MashResampling nor MashDecimate but to feed the mesh from the Meshing node directly into Texturing. Note that you can cleaned-up the mesh in Meshlab before Texturing.
