### ISSUE TITLE
stuck at DepthMap

### ISSUE THREAD

**Issue by ssnakee2** [alicevision/meshroom#227] opened 2018-08-30 00:16 UTC
is there a workaround for not having a nividia GPU?

`[10:04:55.800733][error] This program needs a CUDA-Enabled GPU (with at least compute capablility 2.0).`

and CUDA is a nividia thing

I get this when i get to depthmap.
(I have a crappy IGPU i5 i got in 2013 from intel)

**Comment by ChemicalXandco** [comment] 2018-08-30 08:26
No. Even if they did add support for other graphics, the 'crappy IGPU' would take so long, as depth map computation speed is slow enough as it is. You might as well use [Regard3D](http://www.regard3d.org/index.php) if you're into open source or [3D Zephyr](https://www.3dflow.net/3df-zephyr-free/) If you are looking for good free software or [Photoscan](http://www.agisoft.com/) if you want professional.

**Comment by MrMinimal** [comment] 2018-08-30 18:41
It's a shame, I am also stuck with an AMD Vega 64 which could do this in seconds, but I cannot use this software because of CUDA.

**Comment by yann-lty** [comment] 2018-09-05 16:36
Duplicate of https://github.com/alicevision/AliceVision/issues/439

**Closed by yann-lty** 2018-09-05 16:36 UTC
