### ISSUE TITLE
[bug] Save as window does not appear

### ISSUE THREAD

**Issue by samhodge-aiml** [alicevision/Meshroom#2301] opened 2024-01-18 02:37 UTC
**Describe the bug**
In GUI mode selecting Save As on Ubuntu 22.04 LTS doesnt produce a file dialog

**To Reproduce**
1. Start a template
2. Add Frames
3. Save As....
4. No save file dialog appears

**Expected behavior**
Save as dialog appears

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: Ubuntu 22.04 
 - Python version from meshrom
 - Qt/PySide version from meshroom
 - Meshroom version: 2023.3.0
   - Binary version (if applicable) 2023.3.0

**Additional context**
Works on my other Ubuntu 22.04 system, cannot seem to find the cause with `strace` seems to be in a futex loop not relevant file paths appear.

**Comment by stevealt659** [comment] 2024-01-31 04:03
I have a similar issue. Meshroom 2023.3.0 and Ubuntu Mate 22.04. Trying to save a project brings up a window but typing does not seem to appear and mouse clicks to navigate to folders etc do not seem to do anything. However what I type does seem to take effect when I click on save so it looks to my admittedly uneducated eye like some sort of window response issue. Tried reinstalling CAJA but no impact.

**Comment by stevealt659** [comment] 2024-02-13 06:59
Further to above, have tried using 2023.2.0 and save function works fine in that so it appears to be a change from 2023.2 to 2023.3

**Comment by 3Descape** [comment] 2024-02-19 18:22
I can confirm this bug on Ubuntu 23.04 and Meshroom 2023.3.0

**Comment by thetoivonen** [comment] 2024-02-27 05:23
Confirming on Ubuntu 22.04.4 LTS and Meshroom 2023.3.0.  All of the file browser dialogs seem unresponsive.  Occasionally I can get one to appear by dragging them around aimlessly.  ESC key usually works to close the invisible window and unfreeze the system.

**Comment by Niatgeo** [comment] 2024-03-22 12:18
I am having the exact same issue on Ubuntu 20.04 LTS with 2023.3.0. After a while Ubuntu tells me that Meshroom is not responding. I can use the rest of my sytem but cannot properly close Meshroom.

Meshroom 2023.2.0 works just fine.

**Comment by samhodge** [comment] 2024-03-22 18:39
This issue is two months old and has been confirmed by multiple users, what can we do to get it fixed?

**Comment by iwishiwasaneagle** [comment] 2024-04-01 14:12
Meshroom 2023.3.0 with Ubuntu 23.10, same issue as reported above. Cannot use the file explorer dialogue.

**Comment by gaballench** [comment] 2024-05-20 10:52
Same issue here on Archlinux. Dialogs and emerging windows on Meshroom 2023.3.0 do not work, but they do on Meshroom 2023.2.0. I am using the package provided on each release in this repo.

**Comment by cbentejac** [comment] 2024-06-17 09:10
Hi,

There is indeed an issue with native dialogs on Linux with Qt 5.15 (which is used for Meshroom 2023.3.0) that sometimes causes the file dialogs to be unresponsive. 

A workaround has been merged in the `develop` branch to stop using native dialogs (https://github.com/alicevision/Meshroom/pull/2439) and will be available in the next release.

**Closed by cbentejac** 2024-06-17 09:10 UTC
Labels: bug, linux

**Comment by stevealt659** [comment] 2024-06-17 12:27
Thankyou. Much appreciated.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thetoivonen** [comment] 2024-06-18 12:27
Thank you!

**Comment by samhodge** [comment] 2024-06-18 21:16
Thanks for sorting this out. It might have been tough to determine where the cause was in an upstream library

**Comment by mosiser** [comment] 2025-01-27 16:43
In my case (Kde Neon 6.2 on Ubuntu 24.04), the same problem occurs even with 2023.2, 2023.1 and 2021.1.
Dialogs don't appear, main window became unresponsive, RAM consumption is skyrocketing, until the whole system is not responding anymore.

Everyone seems to have solved it by downloading the previous version, but I haven't...
I hope it is the same problem that has already been solved, waiting for the next release...

**Comment by J3LS** [comment] 2025-03-29 12:31
I have the same problem on 2023.2. Frozen save and save as windows on Linux Mint 22.1 xfce. Changed default browser to a few different apps, same. 
Didn't try other MR versions as also use the free Android version of Kiri which is quite good and a good stand in if you are ok with the limits.
I'll try the next version. Just no time to fiddle with this.
